server:
  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  server:
    enableSelfPreservation: true	
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 3
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
